'''this code was written by Oscar Blessed to prompt the user to give a list of numbers which can then be properly sorted out by the program'''
our_list = []
# this declares an empty list which we will get user input into

name = str(input("\nHello there, may I know your name? "))
print("Oh hi " + name.capitalize())


userval = eval(
    input("Please input a random number you'd like to be in your list "))
our_list.append(userval)
# this adds the first user input to the end of the list

userval = eval(input("\nNow input another number "))
our_list.append(userval)
# this equally adds the second user input to the end of the list

userval = eval(input("\nNow input a third number "))
our_list.append(userval)
# this adds the user's third input to the end of the list

userval = eval(input("\nNow also input a fourth number "))
our_list.append(userval)
# this adds the user's fourth input to the end of the list

print("This is the list generated by you: \n")
print(our_list)
# this gives the initially generated list

for i in our_list:
    if i > 10:
        our_list[our_list.index(i)] = 10
# print(our_list.index(i))


print("Final result: ")
print(our_list)
